def getLSenderPayoffs(lCost, llSender, lhSender, lReceiverProp, hReceiverProp, lReveal):
    al = lReceiverProp*llSender #Accepted by low
    ah = hReceiverProp*lhSender
    
    payoffs =  [[[[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]],
                  #medium normal
                 [[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]],
                  #medium hidden
                 [[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]]],
            #low normal
                [[[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]],
                 #medium normal
                 [[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]],
                #medium hidden
                [[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]]],
            #low hidden
                [[[[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]]],
                  #medium normal
                [[[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]]],
                   #medium hidden
                [[[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]],
                  [[al+ah, al+ah*lReveal, al+ah*lReveal, al],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [al*lReveal+ah, al*lReveal+ah*lReveal, al*lReveal+ah*lReveal, al*lReveal],
                   [ah, ah*lReveal, ah*lReveal, 0]]]]]
    
    for index1, LSmove in enumerate(payoffs):
        for index2, MSmove in enumerate(LSmove):
            for index3, HSmove in enumerate(MSmove):
                for index4, LRmove in enumerate(HSmove):
                    for index5, payoff in enumerate(LRmove):
                        if index1 > 0:
                            payoffs[index1][index2][index3][index4][index5] -= lCost
    
    return payoffs
    
def getMSenderPayoffs(mCost, mlSender, mhSender, lReceiverProp, hReceiverProp, mReveal):
    al = lReceiverProp*mlSender
    ah = hReceiverProp*mhSender
    
    payoffs =  [[[[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]],
                  #medium normal
                 [[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]],
                 #medium hidden
                 [[[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]]]],
            #low normal
                [[[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]],
                  #medium normal
                 [[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]],
                 #medium hidden
                 [[[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]]]],
            #low hidden
                [[[[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]],
                  [[al+ah, al, al, al],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0],
                   [ah, 0, 0, 0]]],
                  #medium normal
                 [[[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]],
                  [[al+ah, al+ah, al, al],
                   [al+ah, al+ah, al, al],
                   [ah, ah, 0, 0],
                   [ah, ah, 0, 0]]],
                 #medium hidden
                 [[[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]],
                  [[al+ah, al+ah*mReveal, al+ah*mReveal, al],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [al*mReveal+ah, al*mReveal+ah*mReveal, al*mReveal+ah*mReveal, al*mReveal],
                   [ah, ah*mReveal, ah*mReveal, 0]]]]]

    for index1, LSmove in enumerate(payoffs):
        for index2, MSmove in enumerate(LSmove):
            for index3, HSmove in enumerate(MSmove):
                for index4, LRmove in enumerate(HSmove):
                    for index5, payoff in enumerate(LRmove):
                        if index2 > 0:
                            payoffs[index1][index2][index3][index4][index5] -= mCost
                            
    return payoffs
    
def getHSenderPayoffs(hCost, hlSender, hhSender, lReceiverProp, hReceiverProp, hReveal):
    al = lReceiverProp*hlSender #accepted by low
    ah = hReceiverProp*hhSender
    
    payoffs = [[[[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium normal
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium hidden
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]]],
            #low normal   
               [[[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium normal
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium hidden
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]]],
            #low hidden
               [[[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium normal
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]],
                #medium hidden
                [[[al+ah, al, al, al],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0],
                  [ah, 0, 0, 0]],
                 [[al+ah, al+ah, al, al],
                  [al+ah, al+ah, al, al],
                  [ah, ah, 0, 0],
                  [ah, ah, 0, 0]],
                 [[al+ah, al+ah*hReveal, al+ah*hReveal, al],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [al*hReveal+ah, al*hReveal+ah*hReveal, al*hReveal+ah*hReveal, al*hReveal],
                  [ah, ah*hReveal, ah*hReveal, 0]]]]]
    
    for index1, LSmove in enumerate(payoffs):
        for index2, MSmove in enumerate(LSmove):
            for index3, HSmove in enumerate(MSmove):
                for index4, LRmove in enumerate(HSmove):
                    for index5, payoff in enumerate(LRmove):
                        if index3 > 0:
                            payoffs[index1][index2][index3][index4][index5] -= hCost
                     
    return payoffs
    
def getLReceiverPayoffs(lReveal, mReveal, hReveal, llReceiver, mlReceiver, hlReceiver, lSenderProp, mSenderProp, hSenderProp):
    al = llReceiver*lSenderProp #accept low
    am = mlReceiver*mSenderProp
    ah = hlReceiver*hSenderProp
    
    payoffs = (((((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (ah, ah, ah, ah),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (ah*hReveal, ah*hReveal, ah*hReveal, ah*hReveal),
                  (ah*hReveal, ah*hReveal, ah*hReveal, ah*hReveal),
                  (0, 0, 0, 0))),
                #medium normal
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am, am, am, am),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am+ah, am+ah, am+ah, am+ah),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am+ah*hReveal, am+ah*hReveal, am+ah*hReveal, am+ah*hReveal),
                  (ah*hReveal, ah*hReveal, ah*hReveal, ah*hReveal),
                  (0, 0, 0, 0))),
                #medium hidden
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am*mReveal, am*mReveal, am*mReveal, am*mReveal),
                  (am*mReveal, am*mReveal, am*mReveal, am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am*mReveal+ah, am*mReveal+ah, am*mReveal+ah, am*mReveal+ah),
                  (am*mReveal, am*mReveal, am*mReveal, am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal),
                  (am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal),
                  (0, 0, 0, 0)))),
            #low normal
               ((((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al, al, al, al),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+ah, al+ah, al+ah, al+ah),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+ah*hReveal, al+ah*hReveal, al+ah*hReveal, al+ah*hReveal),
                  (ah*hReveal, ah*hReveal, ah*hReveal, ah*hReveal),
                  (0, 0, 0, 0))),
                #medium normal
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am, al+am, al+am, al+am),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (0, 0, 0, 0),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am+ah*hReveal, al+am+ah*hReveal, al+am+ah*hReveal, al+am+ah*hReveal),
                  (ah*hReveal, ah*hReveal, ah*hReveal, ah*hReveal),
                  (0, 0, 0, 0))),
                #medium hidden
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am*mReveal, al+am*mReveal, al+am*mReveal, al+am*mReveal),
                  (am*mReveal, am*mReveal, am*mReveal, am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am*mReveal+ah, al+am*mReveal+ah, al+am*mReveal+ah, al+am*mReveal+ah),
                  (am*mReveal, am*mReveal, am*mReveal, am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al+am*mReveal+ah*hReveal, al+am*mReveal+ah*hReveal, al+am*mReveal+ah*hReveal, al+am*mReveal+ah*hReveal),
                  (am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal),
                  (0, 0, 0, 0)))),
            #low hidden
               ((((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al*lReveal, al*lReveal, al*lReveal, al*lReveal),
                  (al*lReveal, al*lReveal, al*lReveal, al*lReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (ah+al*lReveal, ah+al*lReveal, ah+al*lReveal, ah+al*lReveal),
                  (al*lReveal, al*lReveal, al*lReveal, al*lReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (ah*hReveal+al*lReveal, ah*hReveal+al*lReveal, ah*hReveal+al*lReveal, ah*hReveal+al*lReveal),
                  (ah*hReveal+al*lReveal, ah*hReveal+al*lReveal, ah*hReveal+al*lReveal, ah*hReveal+al*lReveal),
                  (0, 0, 0, 0))),
                #medium normal
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am+al*lReveal, am+al*lReveal, am+al*lReveal, am+al*lReveal),
                  (al*lReveal, al*lReveal, al*lReveal, al*lReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am+ah+al*lReveal, am+ah+al*lReveal, am+ah+al*lReveal, am+ah+al*lReveal),
                  (al*lReveal, al*lReveal, al*lReveal, al*lReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (am+al*lReveal+ah*hReveal, am+al*lReveal+ah*hReveal, am+al*lReveal+ah*hReveal, am+al*lReveal+ah*hReveal),
                  (al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal),
                  (0, 0, 0, 0))),
                #medium hidden
                (((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal),
                  (al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal+ah),
                  (al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal, al*lReveal+am*mReveal),
                  (0, 0, 0, 0)),
                 ((al+am+ah, al+am+ah, al+am+ah, al+am+ah),
                  (al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal),
                  (al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal),
                  (0, 0, 0, 0)))))
    
    return payoffs

def getHReceiverPayoffs(lReveal, mReveal, hReveal, lhReceiver, mhReceiver, hhReceiver, lSenderProp, mSenderProp, hSenderProp):
    al = lhReceiver*lSenderProp #accept low
    am = mhReceiver*mSenderProp
    ah = hhReceiver*hSenderProp
    
    payoffs = (((((al+am+ah, 0, 0, 0),
                  (al+am+ah, 0, 0, 0),
                  (al+am+ah, 0, 0, 0),
                  (al+am+ah, 0, 0, 0)),
                 ((al+am+ah, ah, 0, 0),
                  (al+am+ah, ah, 0, 0),
                  (al+am+ah, ah, 0, 0),
                  (al+am+ah, ah, 0, 0)),
                 ((al+am+ah, ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, ah*hReveal, ah*hReveal, 0))),
                #medium normal
                (((al+am+ah, am, 0, 0),
                  (al+am+ah, am, 0, 0),
                  (al+am+ah, am, 0, 0),
                  (al+am+ah, am, 0, 0)),
                 ((al+am+ah, am+ah, 0, 0),
                  (al+am+ah, am+ah, 0, 0),
                  (al+am+ah, am+ah, 0, 0),
                  (al+am+ah, am+ah, 0, 0)),
                 ((al+am+ah, am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, am+ah*hReveal, ah*hReveal, 0))),
                #medium hidden
                (((al+am+ah, am*mReveal, am*mReveal, 0),
                  (al+am+ah, am*mReveal, am*mReveal, 0),
                  (al+am+ah, am*mReveal, am*mReveal, 0),
                  (al+am+ah, am*mReveal, am*mReveal, 0)),
                 ((al+am+ah, am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, am*mReveal+ah, am*mReveal, 0)),
                 ((al+am+ah, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0)))),
            #low normal
               ((((al+am+ah, al, 0, 0),
                  (al+am+ah, al, 0, 0),
                  (al+am+ah, al, 0, 0),
                  (al+am+ah, al, 0, 0)),
                 ((al+am+ah, al+ah, 0, 0),
                  (al+am+ah, al+ah, 0, 0),
                  (al+am+ah, al+ah, 0, 0),
                  (al+am+ah, al+ah, 0, 0)),
                 ((al+am+ah, al+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+ah*hReveal, ah*hReveal, 0))),
                #medium normal
                (((al+am+ah, al+am, 0, 0),
                  (al+am+ah, al+am, 0, 0),
                  (al+am+ah, al+am, 0, 0),
                  (al+am+ah, al+am, 0, 0)),
                 ((al+am+ah, al+am+ah, 0, 0),
                  (al+am+ah, al+am+ah, 0, 0),
                  (al+am+ah, al+am+ah, 0, 0),
                  (al+am+ah, al+am+ah, 0, 0)),
                 ((al+am+ah, al+am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+am+ah*hReveal, ah*hReveal, 0),
                  (al+am+ah, al+am+ah*hReveal, ah*hReveal, 0))),
                #medium hidden
                (((al+am+ah, al+am*mReveal, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal, am*mReveal, 0)),
                 ((al+am+ah, al+am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal+ah, am*mReveal, 0),
                  (al+am+ah, al+am*mReveal+ah, am*mReveal, 0)),
                 ((al+am+ah, al+am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al+am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al+am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al+am*mReveal+ah*hReveal, am*mReveal+ah*hReveal, 0)))),
            #low hidden
               ((((al+am+ah, al*lReveal, al*lReveal, 0),
                  (al+am+ah, al*lReveal, al*lReveal, 0),
                  (al+am+ah, al*lReveal, al*lReveal, 0),
                  (al+am+ah, al*lReveal, al*lReveal, 0)),
                 ((al+am+ah, al*lReveal+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+ah, al*lReveal, 0)),
                 ((al+am+ah, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+ah*hReveal, al*lReveal+ah*hReveal, 0))),
                #medium normal
                (((al+am+ah, al*lReveal+am, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am, al*lReveal, 0)),
                 ((al+am+ah, al*lReveal+am+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am+ah, al*lReveal, 0),
                  (al+am+ah, al*lReveal+am+ah, al*lReveal, 0)),
                 ((al+am+ah, al*lReveal+am+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am+ah*hReveal, al*lReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am+ah*hReveal, al*lReveal+ah*hReveal, 0))),
                #medium hidden
                (((al+am+ah, al*lReveal+am*mReveal, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal, al*lReveal+am*mReveal, 0)),
                 ((al+am+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah, al*lReveal+am*mReveal, 0)),
                 ((al+am+ah, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, 0),
                  (al+am+ah, al*lReveal+am*mReveal+ah*hReveal, al*lReveal+am*mReveal+ah*hReveal, 0)))))
                  
    return payoffs
    
    